apiVersion: v2
name: infra
description: A Helm chart for 
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 25.27.0
    condition: prometheus.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 8.5.1
    condition: grafana.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.1.5
    condition: postgresql.enabled
  - name: pgbouncer
    repository: https://icoretech.github.io/helm
    version: 2.3.2
    condition: pgbouncer.enabled
