prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      storageClass: prometheus
      existingClaim: prometheus-pvc
      
grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: grafana
    existingClaim: grafana-pvc

postgresql:
  enabled: false
  fullnameOverride: postgresql
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: alex
    password: alex123
    database: app

pgbouncer:
  enabled: false
  service:
    type: NodePort
  config:
    adminUser: admin
    adminPassword: admin123
    databases:
      app:
        host: postgresql
        port: 5432
      player:
        host: postgresql
        port: 5432
    userlist:
      postgres: SCRAM-SHA-256$4096:f/RKfmxb0GB7Wgx4CgrJ0Q==$rT4D+2DwpwW968DfU2lcPTfbR57bqtz3Q28EUeZ4sKc=:tVnHzfm7Gr90+dCr8yB0sSm9Yxi5X86uF0be3o8EkbM=
      alex: SCRAM-SHA-256$4096:ZPUOPFQ04QpyyhN/w47J/Q==$7xhSqRQoqh8+ilQhpg0zH8xHxjF1BV9A9ajjY0R+wdk=:Ni1JOOQq2GthVDgQYdqU3rfivBOb01g3ETbN21REEe4=

ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: grafana.local
      paths:
        - name: app-grafana
          path: /(.*)
          pathType: Prefix
          port: 80

